### ISSUE TITLE
Sometimes fail to get the error response from Gateway Server

### ISSUE THREAD

**Issue by ghost** [voyagegroup/apns-proxy-server#16]

**Comment by ghost** [comment]
This error caused by failing to read error response.

```
2014-05-06 18:07:20,556 WARNING [Errno 32] Broken pipe
2014-05-06 18:07:20,569 WARNING Traceback (most recent call last):
  File "apns_proxy_server/worker.py", line 90, in run
    self.main()
  File "apns_proxy_server/worker.py", line 113, in main
    self.send(**item)
  File "apns_proxy_server/worker.py", line 133, in send
    self.apns.gateway_server.send_notification_multiple(frame)
  File "/web/httpd_rkgk/apns-proxy-server/lib/python2.6/site-packages/apns.py", line 351, in send_notification_multiple
    self.write(frame.get_frame())
  File "/web/httpd_rkgk/apns-proxy-server/lib/python2.6/site-packages/apns.py", line 149, in write
    return self._connection().write(string)
  File "/usr/lib64/python2.6/ssl.py", line 148, in write
    return self._sslobj.write(data)
error: [Errno 32] Broken pipe
```
