### ISSUE TITLE
Test Failed

### ISSUE THREAD

**Issue by hagino3000** [voyagegroup/apns-proxy-server#30]
```
FAIL: tests.test_worker.test_create_payload_with_too_large_content
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.8/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/virtualenv/python2.7.8/lib/python2.7/site-packages/nose/tools/nontrivial.py", line 67, in newfunc
    raise AssertionError(message)
AssertionError: test_create_payload_with_too_large_content() did not raise PayloadTooLargeError
```

**Comment by hagino3000** [comment]
Fixed on https://github.com/voyagegroup/apns-proxy-server/commit/5858d1b33d37b9333ca153cd92f091bad9537455 

Result
https://travis-ci.org/voyagegroup/apns-proxy-server/jobs/43561971
